Add windows tray example
halildurmus/win32 pull request #139
Opened 2021-01-13 18:24 UTC by ilopX

# Add windows tray example

![image](https://user-images.githubusercontent.com/8049534/104492881-f1090b80-55dc-11eb-830a-7af0cd5c1436.png)

## New Win32api functions:
* Shell_NotifyIcon
* GetSubMenu
* DestroyMenu
* TrackPopupMenuEx

## New Struct:
* NOTIFYICONDATA
* TPMPARAMS

## New constant:
* Shell_NotifyIcon uFlags
* Shell_NotifyIcon WndProc callback msg
* NOTIFYICONDATA::uFlags
* NOTIFYICONDATA::dwState
* NOTIFYICONDATA::dwInfoFlags
* TrackPopupMenuEx: uFlag
* LoadImage: type, fuLoad

2021-01-15 19:29 UTC, timsneath commented
Oooh -- this is cool! Thank you. I'll take a look over it. We're just doing some nasty breaking changes in FFI right now, so that's occupying my attention, but this is perfect!

2021-01-18 18:25 UTC, timsneath commented
```diff
diff --git a/lib/src/structs.dart b/lib/src/structs.dart
index 91553f68..a5057eca 100644
--- a/lib/src/structs.dart
+++ b/lib/src/structs.dart
@@ -3699,14 +3699,15 @@ class NOTIFYICONDATA extends Struct {
   @Uint32()
   external int dwInfoFlags;
 
-  @Uint32()
-  external int guidItem1;
-  @Uint16()
-  external int guidItem2;
-  @Uint16()
-  external int guidItem3;
-  @Uint64()
-  external int guidItem4;
+  external GUID guidItem;
+  // @Uint32()
+  // external int guidItem1;
+  // @Uint16()
+  // external int guidItem2;
+  // @Uint16()
+  // external int guidItem3;
+  // @Uint64()
+  // external int guidItem4;
 
   @IntPtr()
   external int hBalloonIcon;

```

2021-01-18 18:25 UTC, timsneath commented
```diff
diff --git a/lib/src/structs.dart b/lib/src/structs.dart
index 91553f68..a5057eca 100644
--- a/lib/src/structs.dart
+++ b/lib/src/structs.dart
@@ -3699,14 +3699,15 @@ class NOTIFYICONDATA extends Struct {
   @Uint32()
   external int dwInfoFlags;
 
-  @Uint32()
-  external int guidItem1;
-  @Uint16()
-  external int guidItem2;
-  @Uint16()
-  external int guidItem3;
-  @Uint64()
-  external int guidItem4;
+  external GUID guidItem;
+  // @Uint32()
+  // external int guidItem1;
+  // @Uint16()
+  // external int guidItem2;
+  // @Uint16()
+  // external int guidItem3;
+  // @Uint64()
+  // external int guidItem4;
 
   @IntPtr()
   external int hBalloonIcon;

```

2021-01-18 18:26 UTC, timsneath commented
```diff
diff --git a/lib/src/structs.dart b/lib/src/structs.dart
index 91553f68..e42cbc5a 100644
--- a/lib/src/structs.dart
+++ b/lib/src/structs.dart
@@ -3699,14 +3699,7 @@ class NOTIFYICONDATA extends Struct {
   @Uint32()
   external int dwInfoFlags;
 
-  @Uint32()
-  external int guidItem1;
-  @Uint16()
-  external int guidItem2;
-  @Uint16()
-  external int guidItem3;
-  @Uint64()
-  external int guidItem4;
+  external GUID guidItem;
 
   @IntPtr()
   external int hBalloonIcon;

```

2021-01-18 18:56 UTC, timsneath requested changes
This is really nice work -- congrats @ilopX. This is not easy to get right, as I've learned through many hours of trial and error. 

If we can resolve the string item for consistency, I'd be delighted to merge this. Note that I'm using the `no-addressof` branch as the development branch while I wait for .224 to land in in the dev branch (so CI is clean). So, unless that has merged at the time  when you resubmit, it would be great if you can target this at that branch and I'll merge there and then land it all into `master` at the same time. Does that work?

2021-01-18 18:56 UTC, timsneath commented on lib/src/structs.dart
> +  static void _wchar_cpy(Pointer pointer, int memStart, String source) {
This is a neat approach. But there's a similar one in extensions/set_string.dart, and I wonder if we should merge them together. We won't want a static method like this in every extension method that sets strings, I don't think.

2021-01-18 18:56 UTC, timsneath commented on lib/src/structs.dart
> +  // WCHAR szTip[128]
Sorry about all this crud. Inline arrays are coming real soon now (TM): https://github.com/dart-lang/sdk/issues/35763

2021-01-19 16:09 UTC, timsneath approved these changes
Thank you so much! It's really encouraging to see others contribute high-quality code to this repo. I greatly appreciate you taking the time not only to submit a pull request, but to follow along with the changes for FFI and API metadata!

2021-01-19 16:09 UTC, merged

2021-01-19 18:37 UTC, ilopX commented
Thank you. I'm honored that you accepted my pull request. It inspires me a lot.