SetupDiGetDeviceRegistryProperty implementation and add SPDRP constants
halildurmus/win32 pull request #515
Opened 2022-06-21 14:48 UTC by hpstuff

2022-06-21 17:51 UTC, timsneath requested changes
Looks great, modulo a couple of changes. Thanks for your contribution!

2022-06-21 17:51 UTC, timsneath commented on lib/src/constants.dart
> +const CLSCTX_ALL = CLSCTX_INPROC_SERVER | CLSCTX_INPROC_HANDLER | CLSCTX_LOCAL_SERVER | CLSCTX_REMOTE_SERVER;
For consistency, we wrap using `dart format` with lines set to the default of 80 characters.

2022-06-21 17:51 UTC, timsneath commented on lib/src/constants.dart
> +  static const SPDRP_DEVICEDESC = 0x00000000;
For consistency, use the documentation from https://docs.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupdigetdeviceregistrypropertyw for these fields, which is CC licensed. Wrap at 80 characters, and strip out any unnecessary specifics about backward compatibility to older versions prior to Windows 7. You may omit undocumented values such as `SPDRP_UNUSED1` to avoid unnecessary bloat. 

For example:
```dart
  /// The function retrieves a CM_POWER_DATA structure that contains the
  /// device's power management information.
  static const SPDRP_DEVICE_POWER_DATA = 0x0000001E;
```

Thanks! I know it's a pain, but it's worth it for the long run!

2022-06-22 07:46 UTC, hpstuff commented on lib/src/constants.dart
> +const CLSCTX_ALL = CLSCTX_INPROC_SERVER | CLSCTX_INPROC_HANDLER | CLSCTX_LOCAL_SERVER | CLSCTX_REMOTE_SERVER;
yeah I saw it but wasn't able to find documentation about code formatting or something

2022-06-27 08:31 UTC, hpstuff commented
it's should be fine now, let me know if there anything else that I have to do.

2022-07-01 06:25 UTC, timsneath approved these changes
Great! Thank you!

2022-07-01 06:32 UTC, merged